### ISSUE TITLE
How can export each module to its separate file?

### ISSUE THREAD

**Issue by ada** [karlgoldstein/grunt-html2js#28]
Im using grunt-angular-builder to concat and minify AngularJs application. However this plugin requires only one module definition per file. 

How could I fix this problem?

**Comment by worldspawn** [comment]
Seconded. You can do this via the _gulp_ equivalent. I had it going so each template was jsified and then added as a script reference in the index.html file (via injector). usemin would then bundle them up on build.

One benefit was I could watch html files and regen only the changed/new html file rather than every single one.

Defining every html file as a task in the gruntfile is no solution.

**Comment by worldspawn** [comment]
Soo... I wrote this and slapped in my copy of html2js

``` js
if (options.perFileOutput) {
      this.files.forEach(function(f) {
        var moduleName = f.moduleName;

        f.src.filter(existsFilter).map(function(filepath) {
          var name = normalizePath(path.relative(options.base, filepath));
          var content = getContent(filepath, options);

          var output = '(function() {\n' +
          '\tvar module;\n' +
          '\ttry {\n' +
          '\t\tmodule = angular.module(' + options.quoteChar + moduleName + options.quoteChar + ');\n' +
          '\t} catch (e) {\n' +
          '\t\tmodule = angular.module(' + options.quoteChar + moduleName + options.quoteChar + ', []);\n' +
          '\t}\n' +
          '\tmodule.run([' + options.quoteChar + '$templateCache' + options.quoteChar + ', function ($templateCache) {\n' +
          '\t\t$templateCache.put(' + options.quoteChar + name + options.quoteChar + ', ' + options.quoteChar + content + options.quoteChar + ');\n' +
          '\t}]);\n' +
          '})();';

          grunt.file.write(f.dest + name + '.js', grunt.util.normalizelf(output));
        });
      });
    }
```

So `perFileOutput` isn't an option that exists at the moment. I didn't real deal with the *else* case either.

It doesn't check for coffee.

I expects a `moduleName` value to be defined in each file set. Output is the dest (must have trailing slash) + the normalised path to the file with `.js` appended. eg `scripts/components/test.html.js'

**Comment by karlgoldstein** [comment]
@worldspawn: would you mind putting this into a PR (ideally with a unit test)?  I'd be happy to review and merge it.

**Comment by worldspawn** [comment]
Yeh I could if you describe how you want it to work. I was thinking if perFileOutput is true it won't ever run the current loop, this negates the usefulness of some of the other options such as `options.module` `options.singleModule` `options.fileHeadingString` `options.fileFooterString` and perhaps some others. And I dont know coffee script syntax
