### ISSUE TITLE
Parse Error when using < in angular expression

### ISSUE THREAD

**Issue by sroe** [karlgoldstein/grunt-html2js#60]
Hi,
when I'm using < (less than) operator in an expression e.g. 
`{{ 4 < 5 }}`
 then I get verbose output:
`Parse Error: < 5 }}`
So are angular expressions not fully supported :cry: ?

**Comment by karlgoldstein** [comment]
Please provide a stack trace if you have one.

**Comment by sroe** [comment]
Okay, thats weird, if I copy the files to a clean project folder, install new grunt, new html2js there is no Parse Error with the exact same HTML files?!
And after updating my node modules I get now a Recursive process.nextTick detected Message:
`$ grunt html2js --stack
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded`
The Part with warning is repeated several times, I copied only a few messages.

But at the moment I will use my workaround with copying the files to the clean project folder. 

After deleting my node_modules folder I run npm install and then my task. And I can't believe it but it has 'Running "html2js:main" (html2js) task
Successfully converted 15 html templates to js.`.
So it maybe had something to do with my grunt version? I have tried updating my modules, but it hasn't updated anything.

Sorry for wasting your time!

**Comment by sroe** [comment]
I hit that issue again, now I know it has to do with htmlmin. I have used this configoptions:
```javascript
htmlmin: {
    removeComments: true
}
```
Using --stack --verbose for grunt does only show: 
```javascript
Running "html2js:main" (html2js) task
Verifying property html2js.main exists in config...OK
Files: Test.html, applicationname.html -> tmp/templates.js
Options: base="src", module="templates-main", quoteChar="\"", fileHeaderString="
Reading Test.html...OK
Warning: Test.html
Parse Error: < 5 }}
</body>
</html> Use --force to continue.

Aborted due to warnings.
```

**Comment by sroe** [comment]
Okay I can close it again cause #42 also relates to htmlmin Problems :-1:

**Comment by klaimmore** [comment]
In recent versions of html-minifier you can actually ignore such fragments.
html2js should update to a more recent version.

**Comment by rquadling** [comment]
https://github.com/rquadling/grunt-html2js/issues/96#issuecomment-313624586
