### ISSUE TITLE
Module names all start with "../" 

### ISSUE THREAD

**Issue by germanger** [karlgoldstein/grunt-html2js#61]
This is the structure of my folder:

    -index.html
    -Gruntfile.js
    -views (directory)
    -js (directory)
         -controllers (directory)
         -directives (directory)
         -filters (directory)
         -app.js
         -routes.js

Given the path relation between my views and my "index.html", all views should be called liked this:

       templateUrl: 'views/some-view.html'

And that is exactly how I call them from my "routes.js" and in controllers.
It works as expected.

With that said, now I'm trying to use "grunt-html2js".
I've tried the following cases in my Gruntfile.js

Case 1:

        html2js: {
            options: {
                module: 'myApp.templates',
            },
            main: {
                src: ['views/*.html'],
                dest: 'views/all-views.js'
            }
        },

Case 2:

                src: ['views/*.html'],
                dest: 'all-views.js'

Case 3:

                src: ['views/*.html'],
                dest: 'build/all-views.js'

And, in all of the cases, the result is that the name of the generated modules starts with `"../"`, eg:

         angular.module('myApp.templates', ['../views/some-modal.html', '../views/other-modal.html', .... etc

As written before: **I don't need those two dots!** 
Question: ...how can I configure "grunt-html2js" correctly?

**Comment by germanger** [comment]
I solved this way, but is not very elegant, so I hope theres another way:

            options: {
                rename: function (moduleName) {
                    return moduleName.replace('../', '');
                },
                module: 'myApp.templates',
            },

**Comment by sroe** [comment]
You just need to specify the base argument.
In your case the current workingdir.

**Comment by hhursev** [comment]
@germanger, yeah add

    options: {
       .......
       base: 'views/'
    },

and this is probably the desired result you're willing for

**Comment by germanger** [comment]
Thanks @hhursev, that worked perfectly.
