### ISSUE TITLE
Update version of Jade

### ISSUE THREAD

**Issue by RevanProdigalKnight** [karlgoldstein/grunt-html2js#71]
The currently required version of jade in turn requires an outdated version of acorn, which has a regex that throws a `Range out of order in character class` error, causing me to be unable to run grunt.

**Comment by matthewleon** [comment]
This is addressed in my pull request: https://github.com/karlgoldstein/grunt-html2js/pull/72

**Comment by RevanProdigalKnight** [comment]
Finally got a chance to actually test the updated version - thanks!
