### ISSUE TITLE
Add option to use existing module

### ISSUE THREAD

**Issue by Jandalf** [karlgoldstein/grunt-html2js#73]
I would really like an option like `useExistingModule` that will in conjunction with `singleModule: true` use a `angular.module(targetModule).run(...)` instead of `angular.module(targetModule, []).run(...)` definition. because now I need to dynamically add the template module as a dependency if i'm in production mode (I only use html2js in production).

I could do a PR if you want.

**Comment by karlgoldstein** [comment]
Sure, please submit a PR with a unit test and an update to the options
documentation, and I'll merge it. Thanks.

On Mon, Jul 20, 2015 at 3:12 AM, Jan <notifications@github.com> wrote:

> I would really like an option like useExistingModule that will in
> conjunction with singleModule: true use a
> angular.module(targetModule).run(...) instead of angular.module(targetModule,
> []).run(...) definition. because now I need to dynamically add the
> template module as a dependency if i'm in production mode (I only use
> html2js in production).
>
> I could do a PR if you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karlgoldstein/grunt-html2js/issues/73>.
>



-- 
--Karl--

**Comment by Jandalf** [comment]
closed with version 0.3.4 (PR #74)
